MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: jamia
MYSQL_USER: root
MYSQL_PASSWORD: password

ACTIVE_PROFILE: dev
CONTAINER_PORT: 8080

MAIL_HOST: ${ MAIL_HOST }
MAIL_PORT: ${ MAIL_PORT }
MAIL_USERNAME: ${ MAIL_USERNAME }
MAIL_PASSWORD: ${ MAIL_PASSWORD }
MAIL_VERIFICATION_HOST: ${ MAIL_VERIFICATION_HOST }

JWT_EXPIRATION: 86400000
JWT_SECRET: ${JWT_SECURE_SECRET}