MYSQL_HOST: ${ MYSQL_HOST }
MYSQL_PORT: ${ MYSQL_PORT }
MYSQL_DATABASE: ${ MYSQL_DATABASE }
MYSQL_USER: ${ MYSQL_USER }
MYSQL_PASSWORD: ${ MYSQL_PASSWORD }

ACTIVE_PROFILE: prod
CONTAINER_PORT: 8080
APPLICATION_NAME: Spring Security

MAIL_HOST: ${ MAIL_HOST }
MAIL_PORT: ${ MAIL_PORT }
MAIL_USERNAME: ${ MAIL_USERNAME }
MAIL_PASSWORD: ${ MAIL_PASSWORD }
MAIL_VERIFICATION_HOST: ${ MAIL_VERIFICATION_HOST }

JWT_EXPIRATION: ${ JWT_EXPIRATION }
JWT_SECRET: ${JWT_SECRET}

#--------------
# # logging
#--------------
logging:
  file:
    name: logs/${APPLICATION_NAME}.log
    max-size: 10MB
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    org:
      springframework:
        data: ERROR
        jdbc:
          core:
            jdbcTemplate: ERROR
      hibernate:
        SQL: ERROR
        type:
          descriptor.sql.BasicBinder: ERROR