MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: jamia
MYSQL_USER: root
MYSQL_PASSWORD: password

ACTIVE_PROFILE: dev
CONTAINER_PORT: 8080

MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: jetbrainsthunder@gmail.com
MAIL_PASSWORD: aencelmjnwnjmwpp
MAIL_VERIFICATION_HOST: http://localhost:8080

JWT_EXPIRATION: 86400000
JWT_SECRET: ${JWT_SECURE_SECRET:REV5rxkVgfUn6lCfWGwuNhsJEowXGDJAow4qUrmu24LbvCbfFNgBoB085o2kbUeBy7e4x444Sar5vPfve3BmAx444Sar5vPfve3BmA}