version: "3.8"

services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - symfony

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://user:password@database:3306/database
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/backend
    networks:
      - symfony