version: "3.8"

services:
  database:
    image: mysql
    container_name: database
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - symfony

  backend:
    image: public.ecr.aws/h0q9m0e4/jamia-akbira:latest
    container_name: backend
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - backend_logs:/app/logs
    networks:
      - symfony

volumes:
  database_data:
  backend_logs:

networks:
  symfony:
    driver: bridge
